name: Williamsburg
description: Coffee Roasters in Shanghai
markdown: redcarpet
permalink: /:categories/:title

production_url : http://wcoffeeroasters.com

BASE_PATH : http://wcoffeeroasters.com

menuitems:
  about:
    en: venues
    ch: 关于
  coffees:
    en: coffee
    ch: 咖啡
  services:
    en: souk
    ch: 教育
  news:
    en: news
    ch: 新闻



