name: Williamsburg
description: Coffee Roasters in Shanghai
markdown: redcarpet
permalink: /:categories/:title

production_url : http://biggestT.github.io/williamsburg

BASE_PATH : false

menuitems:
  about:
    en: about
    ch: 关于
  coffee:
    en: coffee
    ch: 咖啡
  buy:
    en: buy
    ch: 买
  news:
    en: news
    ch: 新闻


