name: Williamsburg
description: Coffee Roasters in Shanghai
markdown: redcarpet
permalink: /:categories/:title

production_url : http://wcoffeeroasters.com

BASE_PATH : http://wcoffeeroasters.com

menuitems:
  about:
    en: venues
    ch: 关于
  coffee:
    en: coffees
    ch: 咖啡
  education:
    en: tips
    ch: 教育
  buy:
    en: buy
    ch: 买
  news:
    en: news
    ch: 新闻



